import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import {
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
  ClerkProvider,
} from "@clerk/nextjs";
import { env } from "@/env";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <ClerkProvider
          publishableKey={env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
          signInUrl={env.NEXT_PUBLIC_CLERK_SIGN_IN_URL}
          signUpUrl={env.NEXT_PUBLIC_CLERK_SIGN_UP_URL}
        >
          <TRPCReactProvider>
            <header className="flex w-full items-center justify-between p-4">
              <nav className="flex items-center gap-4 text-sm">
                <a href="/transactions" className="hover:underline">
                  Transactions
                </a>
                <a href="/import" className="hover:underline">
                  Import
                </a>
                <a href="/rules" className="hover:underline">
                  Rules
                </a>
                <a href="/review" className="hover:underline">
                  Review
                </a>
              </nav>
              <SignedOut>
                <SignInButton mode="modal" />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>
            {children}
          </TRPCReactProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
